improve cd workflow

diff --git a/.github/workflows/cd.yaml b/.github/workflows/cd.yaml
--- a/.github/workflows/cd.yaml
+++ b/.github/workflows/cd.yaml
@@ -3,7 +3,6 @@ name: terraform-cd
 on:
   push:
     branches: ["main"]
-    tags: "[0-9]*.[0-9]*.[0-9]*"
     paths:
       # only rebuild when app code changes
       - "terraform/**/*"
@@ -11,6 +10,8 @@ on:
       - "!terraform/backend.sh"
       - "!terraform/delete-backend.sh"
       - "!terraform/Taskfile.yaml"
+  release:
+    types: [published]
   pull_request:
   workflow_dispatch:
 
@@ -18,8 +19,6 @@ jobs:
   terraform:
     name: Terraform
     runs-on: ubuntu-latest
-    env:
-      TERRAFORM_SA_KEY: ${{ secrets.TERRAFORM_SA_KEY }}
     defaults:
       run:
         working-directory: terraform/envs/staging
@@ -31,3 +30,91 @@ jobs:
         uses: hashicorp/setup-terraform@v3
         with:
           terraform_wrapper: false
+
+      - name: Authenticate to GCP
+        uses: google-github-actions/auth@v3
+        with:
+          credentials_json: ${{ secrets.TERRAFORM_SA_KEY }}
+
+      - name: Terraform Format
+        id: fmt
+        run: terraform fmt -check
+
+      - name: Terraform Init
+        id: init
+        run: terraform init
+
+      - name: Terraform Plan
+        id: plan
+        if: github.event_name == 'pull_request'        # Issue terraform plan only for pull requests
+        run: terraform plan -no-color
+        continue-on-error: true
+
+      # Pull results from terraform plan and display in github actions interface
+      - uses: actions/github-script@0.9.0
+        if: github.event_name == 'pull_request'
+        env:
+          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+
+            <details><summary>Show Plan</summary>
+
+            \`\`\`${process.env.PLAN}\`\`\`
+
+            </details>
+
+            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+
+              
+            github.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: output
+            })
+
+      # If plan outcome is a failure, stop the workflow
+      - name: Terraform Plan Status
+        if: steps.plan.outcome == 'failure'
+        run: exit 1
+
+      # TODO
+      #- uses: actions/setup-go@v2
+      #  with:
+      #    go-version: '^1.15.5'
+      #    
+      #- name : Terratest Execution
+      #  if: github.event_name == 'pull_request'
+      #  working-directory: 08-testing/tests/terratest
+      #  run: |
+      #    go test . -v timeout 10m
+
+      # If worklow was triggered but release tag - set to production env
+      # If workflow was triggered by push to main - set to staging env
+      # Otherwise, set to unknown
+      - name: Check tag
+        id: check-tag
+        run: |
+          if [[ ${{ github.ref }} =~ ^refs\/tags\/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then echo ::set-output name=environment::production
+          elif [[ ${{ github.ref }} == 'refs/heads/main' ]]; then echo ::set-output name=environment::staging
+          else echo ::set-output name=environment::unknown
+          fi
+
+      # Aply staging env for a push to main (checked by check-tag job)
+      - name: Terraform Apply Staging
+        working-directory: terraform/envs/staging
+        if: steps.check-tag.outputs.environment == 'staging' && github.event_name == 'push'
+        run: terraform apply -auto-approve
+
+      # Apply production env for a release tag (checked by check-tag job)
+      - name: Terraform Apply Production
+        working-directory: terraform/envs/production
+        if: steps.check-tag.outputs.environment == 'production' && github.event_name == 'release'
+        run: |
+          terraform init
+          terraform apply -auto-approve
